### PR TITLE
leave community fix

### LINKED ISSUE #194: fix: cannot leave community because of insuffient balance?
@rperez89 will check if the issue persists and get the reproduce steps to us decide if that will go to Alpha or Beta.

### PR DESCRIPTION
**Pull request by rperez89**
This closes #194

### CODE REVIEW

File: apps/web/components/RegisterMember.tsx [hunk 1]
```diff
@@ -102,6 +102,9 @@ export function RegisterMember({
     chainId: chainId || 0,
   });
 
+  console.log("accountTokenBalance ", accountTokenBalance);
+  console.log("registerToken ", registerToken);
+
```
Comment (kamikazebr) [inline apps/web/components/RegisterMember.tsx:107]: maybe clean up or leave to be changed for Sentry

**Review by kamikazebr — APPROVED** [review]
LGTM not tested

**Review by kamikazebr — CHANGES_REQUESTED** [review]
Still cannot leave community

**Review by kamikazebr — APPROVED** [review]
Worked but after 1min delay even with refresh
